### PR TITLE
Add  smart action guard (CanExcute) feature support.

### PR DESCRIPTION
**Pull request by CodingOctocat**
I'm a noob (and lazy), and I wanted to make MethodBinding more like a simplified version of the ICommand pattern, and I tried to write code:

Auto match CanExcute method based on name convention.

```
<!-- match Hello() and allways can excute -->
<Button MouseDoubleClick="{s:MethodBinding Hello}" />

<!-- match SayHello() with CanSayHello() -->
<Button MouseDoubleClick="{s:MethodBinding SayHello}" />

<!-- match SayHello(string) with CanSayHello(parameters) -->
<Button MouseDoubleClick="{s:MethodBinding SayHello, 'Singulink'}" />
```

```
public class ViewModel
{
    public void Hello() { }
    public void SayHello() { }
    public void SayHello(string name) { }

    public bool CanSayHello() { } // parameterless.
    public bool CanSayHello(parameters) { }
}
```

### CODE REVIEW

**Comment by mikernet** [comment]
What is the advantage to this over just checking if the method can execute or not inside the actual method?

**Comment by mikernet** [comment]
I've never been a fan of the janky command implementation that polls the `CanExecute` methods on the VM - I've always found it more sensible to use this method binding along with a binding to `IsEnabled` on controls to a bool property with proper change notifications and such, along with a defensive check in the method to trace attempted calls to it when it shouldn't be called.

If I was going to add command-like support to this then I would probably make it so that you can use `MethodBinding` to bind to the `Command` property on controls so it would tap into the polling/auto-disabling functionality present there, so if you wanted to do a commandy method binding to a button for example, you would do:
```xml
<Button Command="{x:MethodBinding ...}" />
```
It would then try to wire up a `CanExecute` method (and/or a bool property) as well and it would retain normal command behavior. There are some additional considerations that need to be carefully thought through with this approach though, particularly involving inheritance.

**Comment by CodingOctocat** [comment]
> What is the advantage to this over just checking if the method can execute or not inside the actual method?

You are right, I seem to be mimicking the Command interface pattern just out of habit, with not much advantage.
> [ICommand - Should I call CanExecute in Execute? - Stackoverflow](https://stackoverflow.com/a/26552948)

**Comment by CodingOctocat** [comment]
Hi @mikernet
_**[The following content was translated by [DeepL](https://www.deepl.com/translator#)]**_

Recently, I read the [Commanding Overview](https://docs.microsoft.com/en-us/dotnet/desktop/wpf/advanced/commanding-overview?view=netframeworkdesktop-4.8), I think if a control element is `ICommandSource`, then it must have `Click` event, and if I bind Command for it, then it will trigger this command when it is clicked, and WPF can manage its `IsEnabled` state automatically.

So, for the `Click` event binding operation, I will treat it specially, I will create a Command object manually and assign it to the Command property of the control, and for the sake of unifying Markup syntax, other event bindings will also support `CanExecute` (but no Command object will be created)

Also, if I have an event that needs to be bound to SayHello(object sender, EventArgs e), I want Markup to omit {s:EventSeder}, {s:EventArgs}, meaning it can intelligently match parameters and intelligently match overloaded functions. I even tried to imitate [Caliburn.Micro](https://caliburnmicro.com/)'s naming-conventions.

Of course, these features are somewhat destructive and I don't think they are suitable to be merged into Singulink, so I may create a new project.

```CSharp
<Button Click="{s:MethodBinding SayHello}" />

// Ignored. Because the binding gives preference to methods with event-related parameters.
public void SayHello() { ... }
// Priority. Because the method has event-related parameters.
public void SayHello(object sender, EventArgs e) { ... }
```

**Comment by mikernet** [comment]
I'm not sure what you mean. If someone wants a command binding they should be binding to the `Command` property. Auto-wiring enabling functionality when you bind to a click event would be odd. You can detect when the method binding is applied to a Command property and apply the extra enabling functionality in that case. I'm not opposed to doing that, I just haven't implemented it because I don't usually do things that way, but it wouldn't be hard to add. The method binding just needs to provide an ICommand implementation in that case. You don't need to fire off Click events or do anything like that. Commands are used in a bunch of places where click events don't apply.

I discourage binding to EventArgs and EventSender directly unless absolutely necessary so it should generally be a moot point. View models should be view agnostic so I almost always use converters or bind to event args sub-properties as passing those directly in would be an anti-pattern. It should be exceedingly rare that a binding passes event sender or event args directly into the bound method so this seems to me like over-complicating overload resolution in weird ways at the expense of performance for very little gain. 

If you are using this method binding properly and following best practices then you should almost never need to do this. I haven't written a blurb about this yet in the readme but I intend to get around to it to steer people away from doing things the naive way in these cases and instead setup their view models in the proper testable/view-agnostic way.

**Comment by CodingOctocat** [comment]
I think xaml is the best UI language, though a bit redundant, so I'm very eager for a short syntax, even at the expense of many other things.😂If I write the code, I'll come and remind to check it out 👀

Finally, thank you for your guidance.❤️

**Comment by mikernet** [comment]
If you modify the code you PR'd a little bit so it triggers the CanExecute functionality when the binding is applied to a Command property then I will merge it in :)

**Comment by mikernet** [comment]
Give me a bit to work out how it should function, because there are a bunch of details that need to be taken into consideration. I'll post back soon with some specifications.

**Comment by CodingOctocat** [comment]
Ok, I will try to write my idea (but it may not work) and then I will PR my code. If you don't think it should be incorporated, can I create a new open source project?

**Comment by CodingOctocat** [comment]
Oh my gosh, I found out that there are still `InputBindings` in WPF, which means I can't avoid `Command` altogether, so everything I'm doing will be meaningless, I think what I need now is `MethodBinding for Command`.

I had fun gaining some more knowledge this time.(*^▽^*)

**Comment by mikernet** [comment]
That's exactly what I was talking about - adding support for `MethodBinding` on `Command` is the way to do this.

**Comment by mikernet** [comment]
Okay...so...the way this should work is that the `CanExecute` method info should be stored alongside the bound method info. So the 2 dictionaries should go from this:
```cs
//s_singleMethodInfoCache: 
ConcurrentDictionary<(Type TargetType, string MethodName, int ArgCount), MethodInfo>
//s_methodInfoCache:
ConcurrentDictionary<(Type TargetType, string MethodName, Type?[] ArgTypes), MethodInfo>
```
to something like this:
```cs
//s_singleMethodInfoCache:
ConcurrentDictionary<(Type TargetType, string MethodName, int ArgCount), (MethodInfo Method, MethodInfo? CanExecute, bool CanExecuteHasParameters)>
//s_methodInfoCache:
ConcurrentDictionary<(Type TargetType, string MethodName, Type?[] ArgTypes), (MethodInfo Method, MethodInfo? CanExecute, bool CanExecuteHasParameters)>
```
`CanExecute` overload resolution should first prefer a version that takes the same parameters as the bound method, and fall back to a parameterless version.

If the method is invoked when `CanExecute` returns false, I think a message should be output to the trace log.

**Comment by mikernet** [comment]
I'm not entirely sure how to treat `{EventSender}` and `{EventArgs}` bindings when calling a parameterized `CanExecute` method at the moment. Let me think through this a bit more.

**Comment by mikernet** [comment]
Oh wait...I don't think `EventSender` and `EventArgs` really makes sense in the context of a `Command`, so I think maybe we should be outputting an error message to the trace if an attempt is made to bind a method that uses those to a `Command`.

We can still support calling the `CanExecute` method with matching `EventArgs`  / `EventSender` parameters for normal event bindings since we will have those values at the time the event is invoked.

**Comment by CodingOctocat** [comment]
I'll organize my thoughts: at first I found this library because event/command binding was cumbersome：
1. Event Binding:
```Xaml
xmlns:i="http://schemas.microsoft.com/xaml/behaviors"

<i:Interaction.Triggers>
    <i:EventTrigger EventName="DragEnter">
        <i:InvokeCommandAction Command="{Binding DragEnterCommand}" PassEventArgsToCommand="True" />
    </i:EventTrigger>
    <i:EventTrigger EventName="Drop">
        <i:InvokeCommandAction Command="{Binding DropCommand}" PassEventArgsToCommand="True" />
    </i:EventTrigger>
</i:Interaction.Triggers>
```
```CSharp
public MyCommand<DragEventArgs> DragEnterCommand { get; }
public MyCommand<DragEventArgs> DropCommand { get; }

public MainVeiwModel()
{
    DragEnterCommand = new MyCommand(DragEnter);
    DropCommand = new MyCommand(e => Drop(e));
}

private void DragEnter(DragEventArgs e) { ... }
private void Drop(DragEventArgs e) { ... }
```
2. Command Binding:
```Xaml
<Button Command="{Binding LoginCommand}"
        CommandParameter=...>
```
```CSharp
public MyCommand LoginCommand { get; }

public MainVeiwModel()
{
    LoginCommand = new MyCommand(Login, CanLogin);
}

public void Login(...) { ... }
public bool CanLogin(...) { ... }
```

Singulink.MethodBinding has solved EventBinding well, but it can't always avoid writing Command, which is not perfect.
First of all, it loses the advantage of automatically enabling/disabling controls with Command.
Second, Command codes cannot be avoided in the following cases:
```Xaml
<Window.InputBindings>
  <KeyBinding Key="B"
              Modifiers="Control" 
              Command="ApplicationCommands.Open" />
</Window.InputBindings>
```

As far as I can test, Command accepts a property and the following syntax is wrong, so it seems impossible to write Xaml Markup Extension for Command?
```Xaml
<Button Command="{s: MethodBinding LoginCommand, parameter...}" />
```
 
```Xaml
<Window.InputBindings>
  <KeyBinding Key="B"
              Modifiers="Control" 
              Command="{s: MethodBinding DoSomething, parameter...}" />
</Window.InputBindings>
```

Anyway, I want to omit the Command code in the VM. I haven't figured out a way to implement MethodBinding for Command yet.

**Comment by CodingOctocat** [comment]
I came up with a solution(Inspired by: [MVVM event to command binding #3: Attached properties](https://www.mobilemotion.eu/?p=1822) ), custom dependency properties!
```Xaml
<Button s:Command.Execute="Method"
        s:Command.CanExecute="CanMethod" 
        s:Command.Parameter="param"/>
```
`CanExecute` and `Parameter` can be omitted and automatically matched by name convention.

In this way, there is no need to write commands in the VM anymore.

**Comment by mikernet** [comment]
I'm confused. Why would `<Button Command="{s: MethodBinding LoginCommand, parameter...}" />` be invalid?

**Comment by CodingOctocat** [comment]
> I'm confused. Why would be invalid?`<Button Command="{s: MethodBinding LoginCommand, parameter...}" />`

I was careless, if the ProvideValue of the MethodBinding returns a Command, then it works.
Then that's great! The difficulty now is how to dynamically create a corresponding Command from a method.

By the way, I use [AsyncAwaitBestPractices.MVVM](https://github.com/brminnick/AsyncAwaitBestPractices). This allows us to not write the ICommand implementation.

**Comment by mikernet** [comment]
I would suggest not taking a dependency on another library for the `ICommand` implementation, it's not difficult to implement in an optimized way based on our requirements.

**Comment by CodingOctocat** [comment]
Good suggestion.
And I would like to make a note here so I don't forget:

I think it is possible to call `RaiseCanExecuteChanged` after `Execute`, which eliminates the need to manually call `CommandManager.InvalidateRequerySuggested()`.

```CSharp
public void RaiseCanExecuteChanged()
{
    Application.Current.Dispatcher.Invoke(() => CanExecuteChanged?.Invoke(this, null)); 
}
```

> [Why people use CommandManager.InvalidateRequerySuggested() on ICommands?](https://stackoverflow.com/questions/40586345/why-people-use-commandmanager-invalidaterequerysuggested-on-icommands/62275903#62275903)

**Comment by mikernet** [comment]
How would someone call `RaiseCanExecuteChanged()`? The `ICommand` implementation/instance that the method binding extension provides is never exposed to the user so this public member is not required AFAICT as there will be no way for someone to call it.

**Comment by mikernet** [comment]
If a command is executing then you're already on the UI thread so the dispatch won't be necessary.

Is there a test case you are seeing that requires raising `CanExecuteChanged` after the command is executed in order to get proper behavior? The framework's automatic requerying should probably be sufficient for most cases I would think.

**Comment by CodingOctocat** [comment]
There may be a translation error.😂
What I mean is that if we want to implement our own ICommand, I think it could look like this:
```CSharp
void ICommand.Execute(object? parameter)
{
    // some implement codes.
    // ...
   Application.Current.Dispatcher.Invoke(() => CanExecuteChanged?.Invoke(this, null)); 
   //or call  CommandManager.InvalidateRequerySuggested() here.

}
```
In short, I want to avoid manually calling the `CommandManager.InvalidateRequerySuggested()` to update UI state.
But I don't know if that's the right thing to do.

**Comment by mikernet** [comment]
I don't believe it should be necessary to do that during `Execute()`. The command manager should usually be clever enough to requery on its own if something happened during the execution that would change the result of `CanExecute`.

Invoking the dispatcher also isn't necessary. If it turns out for some reason that this is beneficial then `CanExecuteChanged?.Invoke(this, null)` will be sufficient without the dispatcher call.

**Comment by CodingOctocat** [comment]
> [ICommand doesn't update the IsEnabled on a button using CanExecute - Stackoverflow](https://stackoverflow.com/a/23559720)

I have a project where one of the buttons uses Command, but it doesn't update the IsEnabled state of the button in time after it is clicked, and I find that I have to manually activate the window anywhere to get the update, my current solution is to call InvalidateRequerySuggested(), but I don't want to do that because not all Command delays updating the UI state, and I have to test all the button's Command to know where to need call InvalidateRequerySuggested().

**Comment by mikernet** [comment]
That's just the nature of WPF commands, and why I usually avoid them and instead bind `IsEnabled` to a property that can support proper change notifications. I don't think we should be messing with WPFs requery logic on a global level like this that affects everything.

If there's a command in your app that isn't quickly updating its ability to execute then you're probably doing something like async commands or background updates, in which case the above code probably won't actually help.

**Comment by CodingOctocat** [comment]
Gosh, I feel like WPF's Command doesn't seem to have any need to exist. It only brings me cumbersome code. It may be logically elegant, but extremely verbose in code.

That said, Command usually corresponds to the Click event (except for InputBinding which corresponds to events such as KeyDown)
So, if one uses MethodBinding, then there seems to be no need to use Command?

**Comment by mikernet** [comment]
I take back part of my last statement - commands do have proper change notifications, you just have to make sure you raise the `CanExecuteChanged` event, just like for properties you need to make sure you raise the `PropertyChanged` event, but that's not really a problem, that's just how MVVM change notifications work. At some point those events are explicitly triggered by VM code.

The issue with command to method binding here is that we don't really have access to the command instances to raise the notification event directly when code executes that causes it to change. Calling `CommandManager.InvalidateRequerySuggested()` would fix that but I don't think that's a suitable option for general use as it's not great for performance.

I see a couple real potential solutions:

1) Wire up change notifications to the dependency properties that hold method binding parameter values and trigger CanExecute updates when those bindings update for the relevant commands. 
2) Create an `ICanExecuteChanged` interface that can fire change notifications for method bindings the same way property change notifications are fired. Those would then cascade to the commands associated with method bindings on the object.

Doing both those should provide the flexibility needed for any Command based scenario.

**Comment by mikernet** [comment]
When you say:
> I have a project where one of the buttons uses Command, but it doesn't update the IsEnabled state of the button

Do you mean you are using commands normally in that project, or using MethodBinding with modifications you made to support commands?

**Comment by CodingOctocat** [comment]
I using commands normally.
And it leaves my vm with a lot of command properties, and bloated constructors.

So, I'm looking for libraries like MethodBinding for Command.

I have some general ideas and I will try to write the code.

**Comment by CodingOctocat** [comment]
I simply implemented `MethodBinding for Command`, and although the code is a bit lame, it works as follows:

```CSharp
public override object ProvideValue(IServiceProvider serviceProvider)
{
    // ...
    else if (provideValueTarget.TargetObject is DependencyObject target && provideValueTarget.TargetProperty is 
    DependencyProperty dp && dp.PropertyType == typeof(ICommand)) {
        foreach (object? argument in _arguments) {
            var argumentProperty = SetUnusedStorageProperty(target, argument);
            _argumentProperties.Add(argumentProperty);
        }
        return CreateCommand((DependencyObject)provideValueTarget.TargetObject);
}
```

```CSharp
private ICommand CreateCommand(DependencyObject source)
{
    var func = CreateFunc(source);
    var command = new AsyncCommand(func); // Temporary use of `AsyncAwaitBestPractices.MVVM`.
    return command;
}
```

```CSharp
private Func<Task> CreateFunc(DependencyObject source)
{
    async Task Func()
    {
        object? value = CreateAndInvokeMethod(source, source, null);
        if (value is Task t) {
            await t.ConfigureAwait(false);
        }
    }

    return Func;
}
```

```CSharp
// Simply extracted the code you wrote.
private object? CreateAndInvokeMethod(DependencyObject source, object? sender, EventArgs? e)
{
    object arg0 = source.GetValue(_argumentProperties[0]);

    if (arg0 == null) {
        Trace.TraceWarning($"[{nameof(MethodBindingExtension)}] First method binding argument is required and cannot resolve to null - method name or method target expected.");
        return null;
    }

    int methodArgsStart;
    object methodTarget;

    // If the first argument is a string then it must be the name of the method to invoke on the data context.
    // If not then it is the explicit method target object and the second argument will be name of the method to invoke.

    string? methodName;
    Type methodTargetType;

    if ((methodName = arg0 as string) != null) {
        if (source is FrameworkElement element) {
            methodTarget = element.DataContext;

            if (methodTarget == null) {
                Trace.TraceWarning($"[{nameof(MethodBindingExtension)}] Null data context for method '{methodName}' on element '{element.Name}' (type: '{element.GetType()}').");
                return null;
            }

            methodTargetType = methodTarget.GetType();
            methodArgsStart = 1;
        }
        else {
            Trace.TraceWarning($"[{nameof(MethodBindingExtension)}] Method target must be specified on element type '{source.GetType()}' because it is not a FrameworkElement and has no data context.");
            return null;
        }
    }
    else if (_argumentProperties.Count >= 2) {
        methodTarget = arg0;
        methodTargetType = methodTarget.GetType();
        methodArgsStart = 2;

        object arg1 = source.GetValue(_argumentProperties[1]);

        if (arg1 == null) {
            Trace.TraceWarning($"[{nameof(MethodBindingExtension)}] Method target type resolved to '{methodTargetType}', method name resolved to null.");
            return null;
        }

        if ((methodName = arg1 as string) == null) {
            Trace.TraceWarning($"[{nameof(MethodBindingExtension)}] Method target type resolved to '{methodTargetType}', method name must be type '{typeof(string)}' (actual type: '{arg1.GetType()}').");
            return null;
        }
    }
    else {
        Trace.TraceWarning($"[{nameof(MethodBindingExtension)}] Method name must be type '{typeof(string)}' (actual type: '{arg0.GetType()}').");
        return null;
    }

    object?[] arguments = new object[_argumentProperties.Count - methodArgsStart];

    for (int i = methodArgsStart; i < _argumentProperties.Count; i++) {
        object? argValue = source.GetValue(_argumentProperties[i]);

        if (argValue is EventSenderExtension)
            argValue = sender;
        else if (argValue is EventArgsExtension eventArgsEx)
            argValue = eventArgsEx.GetArgumentValue(e, (source as FrameworkElement)?.Language);

        arguments[i - methodArgsStart] = argValue;
    }

    (var methodInfo, bool convertStrings) = GetCachedMethod(methodTarget.GetType(), methodName, arguments);

    if (methodInfo == null)
        return null;

    if (convertStrings) {
        var parameters = methodInfo.GetParameters();

        for (int i = 0; i < arguments.Length; i++) {
            var paramType = parameters[i].ParameterType;

            if (arguments[i] == null) {
                if (paramType.IsValueType && Nullable.GetUnderlyingType(paramType) == null) {
                    Trace.TraceWarning($"[{nameof(MethodBindingExtension)}] Method '{methodName}' (target type '{methodTargetType}') parameter {i + 1} (name: '{parameters[i].Name}', type: '{paramType}') is not assignable to null.");
                    return null;
                }
            }
            else if (paramType != typeof(object) && paramType != typeof(string) && _arguments[i + methodArgsStart] is string stringArg) {
                // The original value provided for this argument was a XAML string so try to convert it
                try {
                    arguments[i] = TypeDescriptor.GetConverter(parameters[i].ParameterType).ConvertFromString(stringArg);
                }
                catch (Exception ex) {
                    Trace.TraceWarning($"[{nameof(MethodBindingExtension)}] Method '{methodName}' (target type '{methodTargetType}') parameter {i + 1} (name: '{parameters[i].Name}', type: '{paramType}') could not be assigned from XAML string argument '{stringArg}': {ex}.");
                    return null;
                }
            }
            else if (!parameters[i].ParameterType.IsInstanceOfType(arguments[i])) {
                Trace.TraceWarning($"[{nameof(MethodBindingExtension)}] Method '{methodName}' (target type '{methodTargetType}') parameter {i + 1} (name: '{parameters[i].Name}', type: '{paramType}') is not assignable from argument type '{arguments[i]!.GetType()}'.");
                return null;
            }
        }
    }

    return methodInfo.Invoke(methodTarget, arguments);
}
```

**Pull request closed without merging**
